# Generated by Django 4.0.6 on 2022-07-22 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_issuedbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedbook',
            name='isbn',
        ),
    ]
